# Generated by Django 5.0.6 on 2024-05-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autName', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('user_email', models.CharField(blank=True, max_length=20)),
                ('user_phoneNumber', models.IntegerField(blank=True, default=0, unique=True)),
                ('user_password', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('publicationDate', models.CharField(blank=True, default='', max_length=20)),
                ('ISBN', models.CharField(blank=True, default='', max_length=13)),
                ('bookGenre', models.CharField(blank=True, default='', max_length=30)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.author')),
            ],
        ),
    ]
